#ifndef AAP_CORE_LOCALDEFINITIONS_H
#define AAP_CORE_LOCALDEFINITIONS_H

#define AAP_PUBLIC_API __attribute__((__visibility__("default")))
#define AAP_OPEN_CLASS

#define AAP_MANAGER_MIDI_BUFFER_SIZE 65536
#define AAP_PLUGIN_PLAYER_DEFAULT_MIDI_RING_BUFFER_SIZE 8192
#define AAP_MANAGER_LOG_TAG "AAPManager"

#endif //AAP_CORE_LOCALDEFINITIONS_H
