#ifndef ANDROIDAUDIOPLUGINFRAMEWORK_ANDROID_AUDIO_PLUGIN_HOST_DESKTOP_H
#define ANDROIDAUDIOPLUGINFRAMEWORK_ANDROID_AUDIO_PLUGIN_HOST_DESKTOP_H
#if !ANDROID

#include "../audio-plugin-host.h"

namespace aap {

} // namespace aap

#endif // ANDROID
#endif // ANDROIDAUDIOPLUGINFRAMEWORK_ANDROID_AUDIO_PLUGIN_HOST_DESKTOP_H

