-keep class androidx.core.app.CoreComponentFactory { <init>(); }
-keep class org.androidaudioplugin.AudioPluginService
-keep class org.androidaudioplugin.hosting.AudioPluginHostHelper
-keep class org.androidaudioplugin.hosting.AudioPluginServiceConnector
-keep class org.androidaudioplugin.AudioPluginServiceHelper
