-keep class androidx.core.app.CoreComponentFactory { <init>(); }
-keep class org.androidaudioplugin.hosting.AudioPluginNativeHostContentProvider
-keep class org.androidaudioplugin.AudioPluginService
-keep class org.androidaudioplugin.hosting.AudioPluginHostHelper
