-keep class androidx.core.app.CoreComponentFactory { <init>(); }
-keep class org.androidaudioplugin.AudioPluginNativeHostContentProvider
-keep class org.androidaudioplugin.AudioPluginService
-keep class org.androidaudioplugin.AudioPluginHostHelper
