name: build

on:
  push:
  pull_request:
  workflow_call:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
    - name: cache AVD
      uses: actions/cache@v4
      env:
        cache-name: cache-avd
      with:
        path: /home/runner/.android/gradle/avd
        key: ${{ runner.os }}-gradle-avd
    - name: cache gradle caches
      uses: actions/cache@v4
      env:
        cache-name: cache-gradle-caches
      with:
        path: /home/runner/.gradle/caches/
        key: ${{ runner.os }}-gradle-caches
    - name: apt install
      run: |
        echo y | sudo apt-get install doxygen libxml2-dev libgrpc++-dev libgrpc-dev libprotobuf-dev protobuf-compiler protobuf-compiler-grpc graphviz cmake ninja-build
    - name: build
      run: ./gradlew build dokkaGenerate publishToMavenLocal
    - name: run instrumented tests (disabled)
      if: false
      # > Gradle was not able to complete device setup for: dev30_google_x86_Pixel_5
      # > The emulator failed to open the managed device to generate the snapshot.
      # also https://github.com/actions/virtual-environments/issues/183
      run:
        ./gradlew testDevice1DebugAndroidTest || exit 1
        ./gradlew testDevice2DebugAndroidTest || exit 1
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: aap-core-apps-and-libs
        path: |
          ./*/build/outputs/aar/*.aar
          samples/*/build/outputs/apk/debug/*.apk

  osx-build:
    name: build on osx
    runs-on: macos-14
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
    - name: cache AVD
      uses: actions/cache@v4
      env:
        cache-name: cache-avd
      with:
        path: /Users/runner/.android/gradle/avd
        key: ${{ runner.os }}-gradle-avd
    - name: cache gradle caches
      uses: actions/cache@v4
      env:
        cache-name: cache-gradle-caches
      with:
        path: /Users/runner/.gradle/caches/
        key: ${{ runner.os }}-gradle-caches
    - name: install deps
      run: |
        brew install doxygen libxml2 ninja graphviz openssl
    - name: build
      run: ./gradlew build dokkaGenerate publishToMavenLocal
      env:
        ANDROID_SDK_ROOT: /Users/runner/Library/Android/sdk
