name: deploy to Maven Central

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: setup gpg necessities
        run: sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > $WORKSPACE/'$SIGNING_SECRET_KEY_RING_FILE'"
        env:
          WORKSPACE: ${{ github.workspace }}
          GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
      - name: rewrite publish-pom.gradle to require signing
        run: |
          sed -i "s/signing {}/signing { sign(publishing.publications) }/" publish-pom.gradle
      - name: publish
        run: ./gradlew --warning-mode=all dokkaHtml sonatypeCentralUpload
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ format('{0}/{1}', github.workspace, secrets.SIGNING_SECRET_KEY_RING_FILE) }}
      - name: upload artifact
        if: false #success()
        uses: actions/upload-artifact@v4
        with:
          name: aap-core-apps-and-libs
          path: |
            ./*/build/outputs/aar/*.aar
            samples/*/build/outputs/apk/debug/*.apk
      # Create release
      - name: Create Release
        uses: ncipollo/release-action@v1
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: ./*/build/outputs/aar/*.aar,samples/*/build/outputs/apk/debug/*.apk
      # Update API reference
      - name: deploy to GitHub Pages
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: androidaudioplugin/build/dokka/html
